import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">BaslineReporting</Link>
        </li>
        <li>
          <Link to="/scheduling">Scheduling</Link>
        </li>
        <li>
          <Link to="/tasklist">Tasklist</Link>
        </li>
        <li>
          <Link to="/demoaccount">DemoAccount</Link>
        </li>
        <li>
          <Link to="/switchaccount">SwitchAccount</Link>
        </li>
        <li>
          <Link to="/graphicalcharts">GraphicalCharts</Link>
        </li>
        <li>
          <Link to="/projectstracking">ProjectsTracking</Link>
        </li>
        <li>
          <Link to="/inventorytrendanalysis">InventoryTrendAnalysis</Link>
        </li>
        <li>
          <Link to="/rolespermissions">RolesPermissions</Link>
        </li>
        <li>
          <Link to="/salesreporting">SalesReporting</Link>
        </li>
        <li>
          <Link to="/employeelogin">Employeelogin</Link>
        </li>
        <li>
          <Link to="/performancetracker">PerformanceTracker</Link>
        </li>
        <li>
          <Link to="/videolibrary">VideoLibrary</Link>
        </li>
        <li>
          <Link to="/signuploginmodule">SignupLoginModule</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
